[Unit]
Requires=damienwen-recover.service
After=damienwen-recover.service
ConditionPathExists=/srv/damienwen/boot-role

[Service]
ExecCondition=/usr/bin/grep --fixed-strings --line-regexp --quiet managed /srv/damienwen/boot-role
